name: Deploy to Ec2

on:
  push:
    branches:
      - main

jobs:
  deploy:
        runs-on: ubuntu-latest
        steps:
           - name: checking out code on runner
             uses: actions/checkout@v4

           - name: login to EC2
             uses: appleboy/ssh-action@v1.0.0
             with:
               host: ${{ secrets.EC2_HOST }}
               username: ${{ secrets.EC2_USER_NAME }}
               key: ${{ secrets.EC2_SSH_KEY }}
               port: 22
               script: |
                 whoami
                 pwd
                 sudo apt-get update
               
