name: Deploy to Ec2

on:
  push:
    branches:
      - main

jobs:
  deploy:
        runs-on: ubuntu-ratest
        steps:
          -namae: print my name
          run: |
             echo "Jitendra"

          -name: current folder
           run: pwd 
          
        
  
